version : '3.7'
services:
  db:
    image: postgres
    networks:
      backend:
        ipv4_address: 192.168.176.2
    environment:
      - POSTGRES_DB=threedeefilesmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./assets/postgres.conf:/etc/postgresql/postgresql.conf
      - ./assets/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf


  rest-api:
    image: rust-backend
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.176.0/24
          gateway: 192.168.176.1
