version : '3.7'
services:
  db:
    image: postgres
    networks:
      - backend
    environment:
      - POSTGRES_DB=threedeefilesmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./assets/postgres.conf:/etc/postgresql/postgresql.conf
      - ./assets/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"

  rest-api:
    image: rust-backend
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
